### ISSUE TITLE
Cannot see gulp tasks & build

### ISSUE THREAD

**Issue by lmcdubo** [angelozerr/jsbuild-eclipse#10]
Hi,

  I installed the release 1.1.0 version of jsbuild and I'm trying to use it to trigger gulp builds on my project.

I have two issues:

1) When I point to the gulpfile.js and do "Run As...->Gulp tasks", I can't seem to be able to pass in parameters to the gulp runner.  So basically I get the "Edit Configuration" window that pops up and, no matter what I put in the Arguments section, it always ignores them and run gulp without arguments, which results in the  Gulp help output coming up instead of running the tasks I pointed to

2)  When I try to open the Build explorer and include my gulpfile as a build file, the included file cannot be expanded to see the child tasks, as described in the Getting started guide.  Basically there are no child tasks shown under the gulpfile.js.  I traced on the tern console, but I see no errors.

A sample of the project can be found in https://github.com/lmcdubo/testApp.git

Any ideas?

Thx
/Sebastien

**Comment by angelozerr** [comment]
@lmcdubo sorry for the delay,  it's a bug when gulpfile.js is not in the root of the project, I will fix soon this problem.
