### ISSUE TITLE
Could not create the view: TernExplorerView

### ISSUE THREAD

**Issue by nimo23** [angelozerr/jsbuild-eclipse#12]
I am using "javascript build eclipse 1.1.0" with "Tern Eclipse IDE 1.1.0" on "Eclipse Mars SR1". After installing "javascript build eclipse 1.1.0" and opening the view "Tern Explorer" (which was renamed from "build explorer"), the following error occurs:

"Could not create the view: tern.eclipse.ide.ui.views.TernExplorerView"

**Comment by angelozerr** [comment]
"Tern Explorer" was renamed to "Tern Outline". So close the bad "Tern Explorer" and open the new view "Tern Outline"

**Comment by nimo23** [comment]
ok. thanks. Would be nice to update documentation.

**Comment by nimo23** [comment]
With a separate "build explorer"-view and "tern-explorer"-view, we had seen all gulp tasks while having another javascript file open in "tern-explorer". Now, this is not possible. I have to click the gulp-file and select the task to build, even I dont want to switch back to another js-file. Am I right? I guess, it would be better to separate build-view and tern-view, so we dont need to switch back and forth between gulpfile and another js-file.

**Comment by angelozerr** [comment]
> ok. thanks. Would be nice to update documentation.

done https://github.com/angelozerr/tern.java/wiki/New-and-Noteworthy-1.1.0#tern-outline

> Now, this is not possible. I have to click the gulp-file and select the task to build, even I dont want to switch back to another js-file.

I don't understand? Tern Outline (which was Tern Explorer) had never displayed tasks?

And Build Explorer exists again?

**Comment by nimo23** [comment]
I have installed "JavaScript Build Eclipse 1.1.0" (and "Tern Eclipse IDE 1.1.0") and there is no "Build-Explorer"-View under "Window"->"Show View"->. It does not exist. Where can I find it?

**Comment by angelozerr** [comment]
It should exists, type in the filter "bui"

**Comment by nimo23** [comment]
No, it really does not exist. Maybe upgrading tern plugin from 1.0.0 to 1.1.0 breaks something. 

![screenshot at jan 19 18-50-28](https://cloud.githubusercontent.com/assets/3045549/12426324/6bff4200-bed9-11e5-8264-4a0e5f723e91.png)

![screenshot at jan 19 18-51-02](https://cloud.githubusercontent.com/assets/3045549/12426332/709c942a-bed9-11e5-84c2-8f1663c2d7f8.png)

By the way, maybe it would be better to merge "JavaScript Build Eclipse 1.1.0" plugin within "Tern Eclipse IDE 1.1.0". When using tern, there is a good chance using gulp or grunt for building, too. Dont you think so? By putting "build-explorer" within tern-plugin, potential version conflicts could be avoided.

**Comment by angelozerr** [comment]
> No, it really does not exist. Maybe upgrading tern plugin from 1.0.0 to 1.1.0 breaks something.

I don't know, but to be honnest with you, I have no time to support that.

> By the way, maybe it would be better to merge "JavaScript Build Eclipse 1.1.0" plugin within "Tern Eclipse IDE 1.1.0".

No I don't want to do that, because MyEclipse, JBoss Tools intergrates Tern IDE but not JSBuild Eclipse. More JSDT Team is working on official Grunt/Gulp support, so I will give up JSBuild Eclipse when JSDT Team wll provide this support.

**Comment by nimo23** [comment]
Ok, I understand. I will do a fresh install. Thanks!
