### ISSUE TITLE
Issue in Eclipse Luna with "Tern - Embed Node JS" block

### ISSUE THREAD

**Issue by johanchouquet** [angelozerr/jsbuild-eclipse#4]
Hi,

thanks for this work.

But i have an issue when trying to add New software with line "Tern - Embed Node.js".

Here is what i get:

![tern - embed node js](https://cloud.githubusercontent.com/assets/1401825/9221499/12693f78-40eb-11e5-94b4-375e8427d6f0.png)

PS: i use Eclipse Luna.

Have you any idea how i can fix this ?
Thanks a lot.

**Comment by angelozerr** [comment]
@pascalleclercq could see this problem please for 1.0.0. It seems that some embed plugins are not hosted http://oss.opensagres.fr/jsbuild-eclipse/1.0.0-SNAPSHOT/plugins/ like tern.eclipse.ide.server.nodejs.embed.linux.gtk.x86

@dargoan I suggest you that you install tern.java before https://github.com/angelozerr/tern.java/wiki/Installation-Update-Site

**Comment by johanchouquet** [comment]
Thanks @angelozerr ! it worked.
But when i create a project, by default, i have an ES 3 dependency for my JS project. Then, if i configure it as a Tern Project, I can choose which ES version i'd like to use (5 or 6).

**Comment by angelozerr** [comment]
> Thanks @angelozerr ! it worked.

Cool!

> But when i create a project, by default, i have an ES 3 dependency for my JS project. Then, if i configure it as a Tern Project, I can choose which ES version i'd like to use (5 or 6).

ES3 dependency comes from JSDT. tern.java doesn't use that. See https://github.com/angelozerr/tern.java/wiki/Tern-&-ECMAScript-support

Please note that ternjs starts supporting ES6 but there are a lot of work again.

I'm working too (for 1.0.0) with Tern Explorer https://github.com/angelozerr/tern.java/wiki/Tern-Outline-support and you will soon ES5 Class displayed in this view.

**Comment by angelozerr** [comment]
Thanks @pascalleclercq for your fix!
