### ISSUE TITLE
Installation Error: Solution not available

### ISSUE THREAD

**Issue by atulvani** [angelozerr/jsbuild-eclipse#5]
I get this error when installing:
"The following solutions are not available: JavaScript Build Eclipse 0.10.0
Proceed with the installation anyways?"

I am using:
Version: Luna Service Release 2 (4.4.2)
Build id: 20150219-0600

And I already have Tern 0.10.0 plugin installed.

**Comment by angelozerr** [comment]
I suppose you try with Marketplace. Please retry it.

If it doesn't work, I suggest you that you install with update site https://github.com/angelozerr/jsbuild-eclipse/wiki/Installation-Update-Site

**Comment by angelozerr** [comment]
None answer. I close this issue.

**Comment by atulvani** [comment]
Sorry about that. The link you provided worked for me. Thanks.

**Comment by angelozerr** [comment]
@atulvani thanks for your answer.
