### ISSUE TITLE
Adding Gulp support to Symfony projects?

### ISSUE THREAD

**Issue by JohnA3** [angelozerr/jsbuild-eclipse#9]
I use the Dubture Symfony2 plugin (http://symfony.dubture.com/) with Eclipse.

In order for it to work, a project has to be 'converted' to a Symfony project.

Looking at this Gulp plugin, IIUC, to get the jsbuild-eclipse Gulp support, you have to convert your project to a Tern project.

So it's either/or.

Is there a way to add the Gulp support to existing Symfony projects?

**Comment by angelozerr** [comment]
> Is there a way to add the Gulp support to existing Symfony projects?

Yes it's possible to do that if http://symfony.dubture.com/ wishes to do that by implementing the following extension point https://github.com/angelozerr/tern.java/wiki/Tern-IDE-Extension#ternnatureadapters

Please create an issue for  http://symfony.dubture.com/ Thanks!
